[project]
name = "24-home-work"
version = "0.1.0"
description = ""
authors = [
    {name = "Vladimir9645",email = "rudoruka@gmail.com"}
]
requires-python = "^3.14"
dependencies = [
    "django (>=6.1.1,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
